---
title: "About"
---

# What is the purpose of this project?

To empower people with knowledge on how to train for long term, sustainable progress, including:

* teach readers about movement and training principles
* empower readers to make decisions about their training
* provide technique instruction on complex lifts
* suggest alternative exercises and when to use them
* address myths about fitness, exercise selection, and nutrition

# Who is the intended audience?

Anyone interested in strength training or fitness who would like to learn more about

* exercise selection
* exercise technique 
* training principles
* nutrition for changing body composition or improving performance
* programming

# Why is this guide being made?

There is too much incomplete or outright dangerous information about training and nutrition circulating in both online and real-life communities. I want to provide an educational resource that helps make decision-making easier for people who are overwhelmed and uncertain about what they should be doing to reach their fitness goals.

# Who is writing it?

I am a [Certified Strength and Conditioning Specialist](https://www.nsca.com/certification/cscs/) (CSCS) through the [National Strength and Conditioning Association](https://www.nsca.com/) (NSCA). I spend a lot of time helping people unlearn suboptimal to outright harmful training and eating habits, and hope that this resource will help both those already struggling as well as those who are just starting out and are unsure of where to turn for guidance. You can learn more about me [here](https://the3dlifeproject.com/), or check out my clients in action [here](https://www.instagram.com/ilonacscs/?hl=en).

# How will this guide be published?

I will be using [Quarto](https://quarto.org/) tools to create, publish, and maintain this project.
