# Setting your shoulder blades

The phrase 'setting your shoulder blades' describes the act of keeping your shoulder blades [retracted](scapretraction.qmd). Some exercises call for the shoulder blades to stay retracted while the shoulder joint moves. 


## Why setting your shoulder blades is important 

The shoulder blade-rib cage junction is a joint which moves independently of the arm-shoulder joint. Locking the shoulder blades during a press has the following benefits:

 gives the shoulder joint a stable platform from which to generate and express force
increases the amount of weight you can press
keeps the shoulder from moving into a weak position at the bottom of the movement 


## When to set your shoulder blades

Different exercises require different types of shoulder blade positioning and movement. It is important to set the shoulder blades for externally loaded [pressing] movements like:
 bench press
dumbbell press
floor press


## How to set your shoulder blades

Retracting the shoulder blades while moving at the shoulder might feel unnatural at first. The following drill will allow you to feel out the movement:

Stand up straight with your arms stretched out in front of you. 
Pull your shoulder blades together. 
Keep elbows straight. 
Imagine you are squeezing a pen between your shoulder blades. 
Practice maintaining the retraction while mimicking a bench pressing motion. 

